FROM flink:1.17.1-scala_2.12

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-flink.txt /requirements-flink.txt
RUN pip3 install --no-cache-dir -r /requirements-flink.txt
