version: "3.9"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
    networks:
      - quantnet
    depends_on:
      - postgres
      - minio
      - redpanda
      - flink-jobmanager
    stdin_open: true
    tty: true

  airflow:
    image: apache/airflow:2.8.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Ho --lastname User --role Admin --email admin@example.com &&
               airflow webserver & airflow scheduler"
    depends_on:
      - postgres
    networks:
      - quantnet

  redpanda:
    image: redpandadata/redpanda:v23.3.5
    command:
      - redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false
    ports:
      - "9092:9092"
      - "8081:8081"
    networks:
      - quantnet

  flink-jobmanager:
    image: flink:1.17.1-scala_2.12
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    ports:
      - "8082:8081"
    networks:
      - quantnet

  flink-taskmanager:
    image: flink:1.17.1-scala_2.12
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    depends_on:
      - flink-jobmanager
    networks:
      - quantnet

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - quantnet

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - quantnet

networks:
  quantnet:
    driver: bridge
