FROM apache/airflow:2.8.1-python3.10

USER root
# Install curl + unzip, download ngrok, install to /usr/local/bin
RUN apt-get update && apt-get install -y curl unzip \
 && curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o /tmp/ngrok.zip \
 && unzip /tmp/ngrok.zip -d /usr/local/bin \
 && rm /tmp/ngrok.zip \
 && chmod +x /usr/local/bin/ngrok \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
