version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redpanda:
    image: redpandadata/redpanda:v23.3.5
    command:
      - redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false
    ports:
      - "9092:9092"
      - "8081:8081"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  airflow-init:
    image: apache/airflow:2.8.1-python3.10
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir -r /requirements-airflow.txt && \
        airflow db init && \
        airflow users create \
          --username admin \
          --password admin \
          --firstname Ho \
          --lastname Admin \
          --role Admin \
          --email admin@example.com
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements-airflow.txt:/requirements-airflow.txt
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.8.1-python3.10
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements-airflow.txt:/requirements-airflow.txt
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redpanda
      - minio
    command:
      - bash
      - -c
      - |
        pip install --no-cache-dir -r /requirements-airflow.txt && \
        airflow webserver & airflow scheduler

  flink-jobmanager:
    image: flink:1.17.1-scala_2.12
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    ports:
      - "8082:8081"
    volumes:
      - ./requirements-flink.txt:/requirements-flink.txt
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir -r /requirements-flink.txt || true
        /docker-entrypoint.sh jobmanager

  flink-taskmanager:
    image: flink:1.17.1-scala_2.12
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    depends_on:
      - flink-jobmanager
    volumes:
      - ./requirements-flink.txt:/requirements-flink.txt
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir -r /requirements-flink.txt || true
        /docker-entrypoint.sh taskmanager

volumes:
  postgres_data:
  minio_data:
