name: Run Colab Scraper

on:
  workflow_dispatch:
    inputs:
      broker_uri:
        description: "localhost:9092"
        required: true

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python deps
        run: pip install papermill yfinance confluent-kafka
      - name: Run notebook
        run: papermill colab_scraper.ipynb colab/output.ipynb -p KAFKA_BROKER "${{ github.event.inputs.broker_uri }}"
