name: Run Papermill Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install papermill ipykernel jupyter
          python -m ipykernel install --user --name=python3

      - name: Run Papermill
        run: |
          papermill colab_scraper.ipynb colab/output.ipynb \
            -p KAFKA_BROKER "test" \
            -k python3

      - name: Upload output notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: colab/output.ipynb
