name: Run Notebook

on:
  workflow_dispatch:
    inputs:
      broker_uri:
        description: "Kafka broker URI"
        required: true

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install papermill yfinance confluent-kafka pandas notebook ipykernel || exit 1
          python -m ipykernel install --user --name=python3

      - name: Run notebook with Papermill
        run: |
          mkdir -p colab
          papermill colab_scraper.ipynb colab/output.ipynb \
            -p KAFKA_BROKER "${{ github.event.inputs.broker_uri }}" \
            --kernel python3

      - name: Upload executed notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: colab/output.ipynb